# docker-compose.yml
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./producer/src:/app/src
      - ./read_queue.py:/app/read_queue.py

  llm:
    build:
      context: .
      dockerfile: LLM/Dockerfile
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./LLM/src:/app/src
      - ./read_queue.py:/app/read_queue.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Example of running multiple producers with different parameters
  producer_news:
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    command: python src/main.py --url "https://news.example.com" --keyword "news"

  producer_blog:
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    command: python src/main.py --url "https://blog.example.com" --keyword "blog"

volumes:
  redis_data: