[pytest]
testpaths = tests
pythonpath = . producer/src scorer/src web_service/src database/src

addopts =
    --cov=util
    --cov=producer/src
    --cov=scorer/src
    --cov=web_service/src
    --cov=database/src
    --cov-report=term-missing
    --cov-fail-under=80
